---
title: "Index"
author: "Rovin Sharma"
date: "8/31/2020"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
bibliography: data/references.bib
---
This contains links for Rovin's genomics labs.

# Labs

1. [Introduction to R and Reproducible Research](lab1_rovinsharma.html)
2. [Github and RStudio](lab2_rovinsharma.html)
3. [Starting with the Data](lab3a_rovinsharma.html)

   [Manipulating Data](lab3b_rovinsharma.html)
4. [Data Wrangling and Graphing COVID-19 Reporting Data Pt 1](lab4_rovinsharma.html)

   [Data Visualization with ggplot2 pt 1](lab4a_rovinsharma.html)
   
   [Data Visualization with ggplot2 pt 2](lab4b_rovinsharma.html)
5. [Data Wrangling and Graphing COVID-19 Reporting Data Pt 2](lab5_rovinsharma.html)
   
   [Extra: Interactive Graphs and Animations](lab5x_rovinsharma.html)
6. [Data Maps and Interactive Graphs from the COVID-19 reporting data](lab6_rovinsharma.html)
7. [RNA-Seq workflow](lab7_rovinsharma.html)
8. [Sequence Alignment, Phylogenetic Analysis and Tree Visualization](lab8_rovinsharma.html)
9. [Regular Expressions](lab9_rovinsharma.html)
10. [Population genomics based on high throughput sequencing](lab10_rovinsharma.html)
11. [Microbiome Analysis using dada2 and phyloseq](lab11_rovinsharma.html)
12.
13. [RMarkdown Website](https://rovinsharma.github.io/rmd-website/index.html)



